### ISSUE TITLE
Add an authority for every school and other people facing public bodies that there are lots of

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#616] opened 2016-09-07 06:05 UTC
A lot of public bodies that are geographically repeated, like hospitals, schools etc. refer to a state level department for handling information request.

@henare and I discussed some pros and cons of this idea in chat, I'll dump that here rather than filling this out now.

Henare Degan [3:45 PM]  
@aidan.archer @equivalentideas either of you done hospitals? https://github.com/openaustralia/righttoknow/pull/609#issuecomment-242253884
 GitHub
Add South Australia by henare · Pull Request #609 · openaustralia/righttoknow · GitHub
This updates the help files with information relevant to South Australia. As per the readme to deploy this we still need to: Upload the new authorities (don't forget state and local government... 

[3:46]  
[I'm back working on https://en.wikipedia.org/wiki/List_of_South_Australian_government_agencies#Department_of_the_Premier_and_Cabinet now]

Luke Bacon [3:48 PM]  
I’ve had a look at some and saved them to review

[3:48]  
I agree that they’re the type of body someone would want to request from and it would be good to have them in the site

[3:49]  
In Tassie they have pages within the health department’s website but not specific email addresses

Henare Degan [3:49 PM]  
Sounds like you'd not want separate bodies in that case - just list them in the notes

[3:50]  
In SA I've seen separate websites (with Virtual Reality and everything) but it's probably the same too

[3:50]  
Then there's another case of Local Health Networks

[3:50]  
gah, it's all very confusing

Luke Bacon [3:51 PM]  
It’s a shame cause it feels like it would be clearer for people if they were a distinct authority

Luke Bacon [3:53 PM]  
@henare thinking this hospitals thing through, what do you think of the position that Right To Know should handle the sending it to the right place (the department) but users should be requesting from the org they know of (the hospital)? So you’d get “Dear Launceston Hospital” and the email would be right2info@health.tas.gov.au. And they would respond saying ‘this is the health department, and yes we do handle the hospital, away we go with the request?

Henare Degan [3:54 PM]  
mmm

[3:54]  
Same thing with every school in Australia? (edited)

Luke Bacon [3:54 PM]  
Yeah I recon

Henare Degan [3:54 PM]  
lol

Luke Bacon [3:54 PM]  
LOL

[3:54]  
Why are you loling me!

Henare Degan [3:54 PM]  
LoL

[3:55]  
That's a lot of schools!

Luke Bacon [3:55 PM]  
:slightly_smiling_face:

[3:56]  
The positives would be that it’d be great for people searching, and maybe better for users in the request process. Cons, we’d have to get that list—having some but not all of a type of thing could get real confusing for people. (edited)

Henare Degan [3:56 PM]  
Of course I like the sentiment of thinking from the requester's perspective but it feels like there'd be hundreds of empty authorities. I... don't know.

[3:56]  
Other cons: lots and lots of authorities (mostly with no requests) for people to wade through

Luke Bacon [3:57 PM]  
Hmmm.

Henare Degan [3:57 PM]  
Lots of authorities to manage (what happens when the department inevitably changes its email address)

[3:57]  
Maybe we should create an issue for this and go through it methodically like we did the state name issue?

Luke Bacon [3:58 PM]  
Ok, maybe one way to test this would be making a little site that had a page for every school in NSW and said “Ask Newtown Public School for documents” or something, and then linked to Right To Know to the ed department and helped a little with the request body. If we started getting lots of traffic through that we might find it useful?

[3:59]  

> Maybe we should create an issue for this and go through it methodically like we did the state name issue?

Yeah that sounds like a good idea.

[4:00]  
I think something that made me think about this was that highschoolers guide to FOI. If we want it to be a more “everyday” thing to request documents from the institutions you interact with in your life, then it helps to be thinking about and contacting them directly rather than an umbrella department.

**Comment by henare** [comment] 2016-09-08 06:13
People definitely want to FOI hospitals: https://www.righttoknow.org.au/request/royal_prince_alfred_hospital_sta

**Comment by henare** [comment] 2016-09-14 02:39
Probably a duplicate of #463.

**Closed as completed by henare** 2016-09-14 02:39 UTC
Labels: authorities
