### ISSUE TITLE
Authority Pages aren't updating with new requests

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#344] opened 2014-05-17 03:52 UTC
https://www.righttoknow.org.au/body/asada isn't showing https://www.righttoknow.org.au/request/afl_asada_joint_investigation_fr, and it should. Guessing this is a cache issue?

**Comment by henare** [comment] 2014-05-18 06:21
It's showing for me [now].

Closing as a duplicate of #313 since they seem to be the same problem.

**Closed as completed by henare** 2014-05-18 06:21 UTC
Labels: bug
