### ISSUE TITLE
The 'other country notice' popup appears, when I'm in Australia, on pages that aren't the home page

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#586] opened 2016-08-04 05:07 UTC
The 'other countries' notice is appearing when I'm in Australian in staging. Oddly it only appears when I'm not on the homepage. It's tells me about an 'important message for visitors outside Australia', which isn't relevant to me.

![screen shot 2016-08-04 at 3 01 20 pm](https://cloud.githubusercontent.com/assets/1239550/17390944/f72d4aae-5a54-11e6-8930-dcbf4b33f32b.png)

**Comment by henare** [comment] 2016-08-04 05:16
My hunch is that a change to the other country processing code means that it's picking up the IP address as localhost from Varnish.

**Comment by henare** [comment] 2016-08-04 05:33
My hunch was wrong. The code [uses `request.remote_ip`](https://github.com/mysociety/alaveteli/blob/0.23.2.4/app/controllers/application_controller.rb#L483) which correctly sets the IP based on X-Forwarded-For. You can see this [in debug](http://test.righttoknow.org.au/admin/debug), it has the correct IP address.

@equivalentideas I can't reproduce this. Can you please test without a VPN?

**Comment by equivalentideas** [comment] 2016-08-04 05:37
> @equivalentideas I can't reproduce this. Can you please test without a VPN?

There's no notice without the VPN. And always a notice with the VPN no matter what country it's set to use.

**Comment by henare** [comment] 2016-08-04 05:37
Sweet! I don't think this is a regression then so I'll close this.

**Comment by henare** [comment] 2016-08-05 04:05
I just saw this in production. Reopening.

**Comment by henare** [comment] 2016-08-05 04:20
Crap. In production `action_dispatch.remote_ip` is localhost. So it is something to do with the Varnish config.

**Comment by henare** [comment] 2016-08-05 04:20
Ahh, HTTP_X_FORWARDED_FOR is localhost - that's not right.

**Comment by henare** [comment] 2016-08-05 05:13
This was a doozy. It turns out that Right To Know production gets proxied twice: Apache (HTTPS) > Varnish > Apache (HTTP). This means the X-Forwarded-For header set by the original Apache hit was being stripped by Varnish and replaced with localhost.

I've updated the Varnish configuration to not sanitise the X-Forwarded-For header on requests for Right To Know production:

```
[snip]
    # Pass through anything that's not Right to Know production
    if (req.http.host != "www.righttoknow.org.au") {
        # Sanitise X-Forwarded-For...
        # Only do this for sites that aren't Right To Know production. This is
        # because it gets proxied twice: Apache > Varnish > Apache so we retain
        # the X-Forwarded-For from the first Apache hit so it gets passed on.
        remove req.http.X-Forwarded-For;
        set req.http.X-Forwarded-For = client.ip;

        return(pass);
    }
[snip]
```

I think that's got it sorted.

**Comment by mlandauer** [comment] 2016-08-10 04:18
I'm seeing this in production :-(

**Comment by henare** [comment] 2016-08-10 04:47
Thanks for reporting this @mlandauer! Do you have a VPN?

**Comment by mlandauer** [comment] 2016-08-10 04:47
Nope, no VPN

**Comment by henare** [comment] 2016-08-10 05:02
@mlandauer and I tried a few different things to reproduce and he now can't see it so we're not sure what's going on. I've asked Twitter to test it too: https://twitter.com/henaredegan/status/763238544751996933

**Comment by henare** [comment] 2016-08-10 06:00
I got 3 helpful responses on Twitter and none of them could see the problem. I'll close this until we hear more reports or can reproduce.

**Comment by equivalentideas** [comment] 2016-08-11 07:29
@Kat had this appear today when at Newtown. No VPN.

**Comment by henare** [comment] 2016-08-15 01:34
This is reliably reproducible at our office in Newtown.

**Comment by henare** [comment] 2016-08-15 05:50
My hunch is that the local geoip database is out of date so I'll investigate that first.

**Comment by henare** [comment] 2016-08-15 05:54
Yep, that looks to be correct. When I query the IP address we're using in Newtown it says we're in Taiwan. I'll see if we can get an updated version of the `geoip-database` package installed.

**Comment by henare** [comment] 2016-08-15 06:03
This fixed it: `sudo aptitude install geoip-database-contrib`

The `geoip-database-contrib` package downloads the binary flavour of the four MaxMind GeoLite databases and keeps them up to date.

After installing this package and restarting I checked my IP address again and I was in Australia, not Taiwan so it should definitely be fixed. I'm also not seeing the message any more.

**Closed as completed** 2016-08-15 06:04 UTC
Labels: bug
