### ISSUE TITLE
Fix broken link to Australian Government Webguide

### ISSUE THREAD

**Issue by katska** [openaustralia/righttoknow#824] opened 2023-12-14 09:02 UTC
Why should I not send PDF documents in FOI responses? [#](https://www.righttoknow.org.au/help/officers#pdf)
The [Australian Government Webguide](http://webguide.gov.au/accessibility-usability/accessibility/pdf-accessibility/) makes it very clear that PDF is not an acceptable format for you to use in the delivery of government information:
PDF does not yet have approved Sufficient Techniques to claim WCAG 2.0 conformance, so it cannot be ‘relied upon’ in the provision of government information.
Write a response in an email as plain text. This is not only a simple and efficient way for you to conform to government guidelines, it is easier and quicker for the recipient to read.

I'm not sure if this is an equivalent page - talks about why PDFs are bad and when to use them

https://www.stylemanual.gov.au/content-types/pdf-portable-document-format

**Comment by katska** [comment] 2024-01-25 06:16
ah yes, still broken. 
Linked to from here:
Why should I not send PDF documents in FOI responses? [#](https://www.righttoknow.org.au/help/officers#pdf)
The [Australian Government Webguide](http://webguide.gov.au/accessibility-usability/accessibility/pdf-accessibility/) makes it very clear that PDF is not an acceptable format for you to use in the delivery of government information:
PDF does not yet have approved Sufficient Techniques to claim WCAG 2.0 conformance, so it cannot be ‘relied upon’ in the provision of government information.
Write a response in an email as plain text. This is not only a simple and efficient way for you to conform to government guidelines, it is easier and quicker for the recipient to read.

**Comment by katska** [comment] 2024-03-19 04:31
Link should go to [The Australian Government Style Manual](https://www.stylemanual.gov.au/content-types/pdf-portable-document-format)

**Comment by benrfairless** [comment] 2024-06-11 04:12
Duplicate of #815

**Closed as completed by benrfairless** 2024-06-11 04:12 UTC
