### ISSUE TITLE
Use Google Docs to render PDFs in HTML view

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#475] opened 2015-04-07 02:53 UTC
WDTK uses Google Docs Viewer to render PDFs, which would be a massive improvement over what we have now. We should consider doing this.

**Comment by equivalentideas** [comment] 2015-04-07 06:27
@maxious mentioned the Office online viewer for Word, Excel and Power Point docs http://products.office.com/en-us/office-online/view-office-documents-online

**Comment by equivalentideas** [comment] 2015-04-07 06:29
Also there's this from #474 :

> Is there a possibility we could use an external doc view like the Internet Archive's or Google Docs, like What Do They Know?

There's the [internet archive’s PDF viewer](https://archive.org/stream/NSW_Pecuniary_Interests_2013-2014/2014-06-30_Hancock_Shelley_pecuniary-interests#page/n3/mode/2up).

**Comment by henare** [comment] 2015-04-09 01:50
Related: https://github.com/mysociety/alaveteli/issues/833

> WDTK uses Google Docs Viewer to render PDFs

The first WDTK request I picked to reproduce this didn't so I'm closing this as cannot reproduce:

https://www.whatdotheyknow.com/request/257035/response/638392/attach/html/2/Response%20all%20information%20to%20be%20supplied.pdf.html

**Closed as completed by henare** 2015-04-09 01:50 UTC

**Comment by henare** [comment] 2015-04-09 04:21
Here's an example of a PDF on RTK using the Docs viewer: https://www.righttoknow.org.au/request/882/response/3196/attach/html/3/December%20Diary.pdf.html
