### ISSUE TITLE
Confirm upload with csv works

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#319] opened 2014-03-27 07:45 UTC
@brfairless in #316 asked: does anyone have a CSV template so I can upload the changes? (to boards)

**Comment by henare** [comment] 2014-03-27 07:53
I notice that yesterday Right To Know was crashing when trying to import some things Ben was uploading. @brfairless - can you share the files you're trying to upload with me so I can check them?

**Comment by benrfairless** [comment] 2014-03-27 07:54
The issue appears to only be related to CSV files I create in MacOS. If I
create exactly the same file in excel in windows 8 there are no issues.

On Thursday, March 27, 2014, Henare Degan notifications@github.com wrote:

> I notice that yesterday Right To Know was crashing when trying to import
> some things Ben was uploading. @brfairless https://github.com/brfairless\- can you share the files you're trying to upload with me so I can check
> them?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/openaustralia/righttoknow/issues/319#issuecomment-38776614
> .

## 

Ben Fairless
ben@fairless.id.au

Sent from my iDevice, please forgive spelling and grammatical errors.

**Comment by kat** [comment] 2014-03-27 07:58
@henare @befairless is braver than me then :-)  I did a 'dry run' upload of a test csv of a couple of agencies, without actually uploading. Overall, I did not find the system's feedback clear or reassuring, and left gaps where I was not sure what would happen if I went ahead with a live upload. I followed the instructions, added an #id column at the head made it look like it was going to upload, but I was not convinced data would not be lost because it still errored in places and the feedback talked about manually deleting entries. ick. https://docs.google.com/a/openaustralia.org/spreadsheet/ccc?key=0Av0JrLy9bmIPdGhyckRPRHNsdDg3ck1vRGVaR1lIeXc&usp=sharing is the doc I exported as csv (from an export from RTK) to dry run.

**Comment by kat** [comment] 2014-03-27 08:02
(I tried a smaller test of a couple of agencies in the same format first BTW)

**Comment by benrfairless** [comment] 2014-03-27 10:03
I'll send you the template I use when I get home @kat (hopefully in the next 2 hours)

**Comment by benrfairless** [comment] 2014-03-28 03:08
@kat this is the template I use: https://drive.google.com/a/openaustralia.org/file/d/0B6FvM3R1FeGaZ01OZHdUV3dhOTQ/edit?usp=sharing

The issue I'm getting at the moment is:

```
ERROR:  duplicate key value violates unique constraint "index_public_bodies_on_url_name"
```

**Comment by henare** [comment] 2014-03-28 05:56
OK I've looked into this a bit more and oh dear, what a frightful mess! :scream: 

What I'm going to do is close this issue (CSV upload _doesn't_ work). I'm going to start by focussing on @brfairless' #320 issue first.

As we encounter more issues we should create focussed, separate issues for them too.

**Closed as completed by henare** 2014-03-28 05:56 UTC

**Comment by benrfairless** [comment] 2014-03-28 05:59
I would Disagree @henare.... Have a look at the timeline, I managed to upload 15 new agencies, are there any issues behind the scenes with those uploads?

**Comment by henare** [comment] 2014-03-28 06:01
Sorry I meant it doesn't work properly :)

I think you've answered my question to @kat over on #312. You've successfully uploaded _new_ public bodies via CSV yes?

**Comment by benrfairless** [comment] 2014-03-28 06:03
Yes. The issue is that the downloaded CSV can't be re-uploaded. see my template above which should help with uploads: https://drive.google.com/a/openaustralia.org/file/d/0B6FvM3R1FeGaZ01OZHdUV3dhOTQ/edit?usp=sharing

**Comment by henare** [comment] 2014-03-28 06:06
Great stuff. I've created another issue about the downloaded CSV: #321
