### ISSUE TITLE
Caches not cleared when a request page changes

### ISSUE THREAD

**Issue by maxious** [openaustralia/righttoknow#313] opened 2014-03-03 06:14 UTC
Add a "clear cache" call for the request URL once an email is received or the request otherwise changes.

Possibly also clear the organisation URL and front page?

**Comment by henare** [comment] 2014-03-03 06:49
Cache was set up by some dunderhead as part of #41. He probably did something silly.

**Comment by henare** [comment] 2014-03-19 03:27
Yikes. This request hasn't been updated in hours: https://www.righttoknow.org.au/request/incident_logs_self_harm_by_minor

We should fix this as a priority.

**Comment by henare** [comment] 2014-03-20 05:27
I've spent an hour or so trying to debug this and I'm stumped. I can't even seem to manually purge items from the Varnish cache :confounded:

**Comment by benrfairless** [comment] 2014-04-14 06:25
I noticed this on staging when creating new requests. If I create a new request, it isn't visible in http://test.righttoknow.org.au/list/all right away. It also doesn't appear in my requests: http://test.righttoknow.org.au/user/ben_fairless_staging/requests

It took about 5 - 10mins for it to appear.

**Comment by henare** [comment] 2014-04-14 07:11
> I noticed this on staging when creating new requests. If I create a new request, it isn't visible in http://test.righttoknow.org.au/list/all right away. It also doesn't appear in my requests: http://test.righttoknow.org.au/user/ben_fairless_staging/requests

That's because the Xapian index only gets updated every 5 minutes: https://github.com/openaustralia/alaveteli/blob/2d677de246f9831c4aa7f3841122a8ccca670600/config/crontab-example#L11

**Comment by henare** [comment] 2014-05-22 22:13
Closing as a duplicate of #259

**Closed as completed by henare** 2014-05-22 22:13 UTC
