### ISSUE TITLE
0.26 - The Drop-downs in the Admin Console Don't work

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#688] opened 2017-04-04 10:52 UTC
The Drop down's in the Admin Bar don't work in 0.26 (Development).

Tested in Google Chrome on MacOS

Production:
<img width="410" alt="dropdown-prod" src="https://cloud.githubusercontent.com/assets/6841582/24653303/dc03f688-1967-11e7-9cba-507423686d08.png">

0.26 Upgrade:
<img width="308" alt="dropdown-0 26" src="https://cloud.githubusercontent.com/assets/6841582/24653304/dc5551ea-1967-11e7-99a0-20cc81260450.png">

**Comment by akve17** [comment] 2017-04-05 07:06
i would like to work on this issue. can you give me some pointers on how to start?

**Comment by EkaterinaSemenova** [comment] 2017-04-05 21:16
Hi @benrfairless ,
I can't reproduce this issue as well as #689 on Alaveteli 0.26.0.0 and 0.26.0.12. Could you please specify which exact version (or commit hash) of Alaveteli you were using and which version (or commit hash) of righttoknowtheme you were using.

**Comment by equivalentideas** [comment] 2017-04-06 03:20
Sounds like a javascript problem to me.

**Comment by henare** [comment] 2017-04-11 07:47
@EkaterinaSemenova are you using our theme with that version of Alaveteli? I think @benrfairless is suggesting it's specific to our theme and that probably means it only happens when you're trying to use the admin bar and you're on a frontend page, i.e. not looking at the admin backend.

**Comment by EkaterinaSemenova** [comment] 2017-04-13 11:21
Hi @henare! I have tested this on Alaveteli tag 0.26.0.0 with righttoknow theme (commit d65bac0). The issue doesn't reproduce in Chrome 57.0.2987 running on Ubuntu. I was not able to reproduce this issue for both admin and user pages. 

![screenshot from 2017-04-13 13-59-34](https://cloud.githubusercontent.com/assets/20787120/25002691/670fd3bc-2054-11e7-8874-a471b6f47a02.png)
![screenshot from 2017-04-13 14-00-09](https://cloud.githubusercontent.com/assets/20787120/25002692/670fd47a-2054-11e7-94a6-5f3a2ac97e72.png)
![screenshot from 2017-04-13 14-00-22](https://cloud.githubusercontent.com/assets/20787120/25002693/67121dfc-2054-11e7-8a62-555a6277eac8.png)

I also have noticed that this menu doesn't work for the first 1-2 seconds until page load had finished. After complete page load everything works fine, but it doesn't sound to me like an issue that should be fixed, does it?

**Comment by henare** [comment] 2017-04-18 01:09
Thanks for testing this @EkaterinaSemenova :+1: I'll close this as "cannot reproduce".

**Closed as completed by henare** 2017-04-18 01:09 UTC
Labels: bug, design, good for first contribution
