### ISSUE TITLE
Style of popup link makes it unreadable

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/righttoknow#585] opened 2016-08-04 04:55 UTC
The style of links in the site "popup"/notice is too low contrast against the green background to be read.

![screen shot 2016-08-04 at 2 52 10 pm](https://cloud.githubusercontent.com/assets/1239550/17390764/73270688-5a53-11e6-8212-52104fa8dc7e.png)
![screen shot 2016-08-04 at 2 52 25 pm](https://cloud.githubusercontent.com/assets/1239550/17390765/7329f30c-5a53-11e6-835c-874f1d3f791f.png)

**Comment by henare** [comment] 2016-08-04 04:56
Duplicate of #578.

**Closed as completed by henare** 2016-08-04 04:56 UTC
Labels: bug, design
